spring.application.name=qrcodeGenerator

# Configuração do banco de dados H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234
spring.sql.init.platform=h2

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Hibernate para criar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

